name: kiran_portfolio_website
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-219.0.dev <4.0.0'

dependencies:
 
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.6
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_animate_on_scroll: ^0.0.2
  flutter_gen: ^5.4.0
  flutter_riverpod: ^2.4.10
  flutter_social_button: ^1.1.4+1
  gap: ^3.0.1
  hovering: ^1.0.4
  responsive_framework: ^1.1.1
  velocity_x: ^4.1.2

dev_dependencies:
  build_runner: null
  flutter_gen_runner: null
  flutter_lints: ^3.0.0

  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/core/gen/
  # line_length: 80 # Optional (default: 80)
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  assets:
    enabled: true

    outputs:
      class_name: MyAssets
      package_parameter_enabled: false
      # Assets.imagesChip
      # style: camel-case
      # Assets.images_chip
      # style: snake-case
      # Assets.images.chip (default style)
      style: dot-delimiter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/tools_images/
